// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiACHHIH1jl2RVVsNv5ngmwDKH0Unqpw8',
    appId: '1:296778432697:web:e684eefc43725fad2a9b68',
    messagingSenderId: '296778432697',
    projectId: 'shopping-app-4910d',
    authDomain: 'shopping-app-4910d.firebaseapp.com',
    storageBucket: 'shopping-app-4910d.firebasestorage.app',
    measurementId: 'G-TBW9GZ2LBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBJgrwvwt_gdRHrzILnuTtEJyPcXsCFZk',
    appId: '1:296778432697:android:7a9dcd6a5c95614f2a9b68',
    messagingSenderId: '296778432697',
    projectId: 'shopping-app-4910d',
    storageBucket: 'shopping-app-4910d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrKzitn5LTi4HXgDG3VHLGvucqCiDJ1XA',
    appId: '1:296778432697:ios:610db81d9b89f8462a9b68',
    messagingSenderId: '296778432697',
    projectId: 'shopping-app-4910d',
    storageBucket: 'shopping-app-4910d.firebasestorage.app',
    iosBundleId: 'com.example.shopingApp',
  );
}
